GET http://localhost:5000/menu

###

POST http://localhost:5000/order

###

POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}